---
- name: Reload systemd and restart pulp workers
  systemd:
    daemon_reload: true
    name: pulpcore-worker@{{ item }}.service
    state: restarted
  with_sequence: 'start=1 count={{ pulp_workers }}'
  become: true
