---
- name: Reload systemd and restart pulp workers
  systemd:
    daemon_reload: true
    name: pulpcore-worker@{{ item.key }}.service
    state: restarted
  with_dict: '{{ pulp_workers }}'
  become: true
