---
- name: Converge
  hosts: pulp
  roles:
    - role: ansible-pulp3
      pulp_config_secret_key: 'aabbccddeeffgghhiijj'
      pulp_config_database:
        default:
          ENGINE: django.db.backends.postgresql
          NAME: 'pulp'
          USER: 'pulp'
          PASSWORD: 'supersecure'
