---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Postgres
      package:
        name: '{{ item }}'
        state: installed
      with_items:
        - postgresql-server
        - postgresql-contrib
    - name: Initiate database
      command: postgresql-setup --initdb --unit postgresql
    - name: Start Postgres
      service:
        name: postgresql
        state: started
