---

- name: Fail when pulp_secret_key is not set
  assert:
    that: pulp_settings.secret_key is defined

- name: Load OS specific variables
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
    - always

# Note: We cannot use `systemd-path search-binaries-default` because
# it wasn't added until systemd 239. Thus no CentOS 7 or Fedora 28
# support, etc.
- name: Enumerate default system PATH
  # pipefail is not needed due to grep's rc, but it resolves ansible-lint 306
  shell: |
    set -o pipefail
    systemctl show-environment | grep -E '^PATH=' | sed 's/PATH=//g'
  args:
    # Debian defaults to bourne, but it doesn't understand pipefail.
    executable: /bin/bash
  changed_when: false
  register: systemd_show_env_path
  check_mode: false

- name: set the default system PATH as a fact
  set_fact:
    default_bin_path: "{{ systemd_show_env_path.stdout }}"


# Try multiple possible names for the rhel7 optional repo until it is found.
# The query ensures that a single string rather than a list of strings is valid.
- include_tasks: rhel7-optional.yml
  with_items: "{{ rhel7_optional_repo }}"
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version|int == 7
    # Works for both strings and lists to make sure not empty
    - rhel7_optional_repo is not none
    - rhel7_optional_repo | length > 0
    # Prevents running again once completed.
    - optional_repo_enabled is not defined

- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: wsgi.yml
