---
# Upstream is slow to accept pull requests.
# Still waiting on the original " Add Fedora support" pull request from ehelms.
#
# https://github.com/geerlingguy/ansible-role-postgresql/compare/master...mikedep333:F30
- src: https://github.com/mikedep333/ansible-role-postgresql
  version: F30
  name: geerlingguy.postgresql
