---
- hosts: all
  vars:
    pulp_source_dir: "/home/vagrant/devel/pulp"
    pulp_secret_key: "unsafe_default"
    pulp_default_admin_password: password
    pulp_install_plugins:
      # pulp-python:
      #   app_label: "pulp_python"
      #   source_dir: "/home/vagrant/devel/pulp_python"
      pulp-file:
        app_label: "pulp_file"
        source_dir: "/home/vagrant/devel/pulp_file"
  pre_tasks:
    - name: Set up Vagrant machine for source installs
      include: vagrant-pretask.yml
  roles:
    - pulp3-postgresql
    - pulp3-workers
    - pulp3-resource-manager
    - pulp3-webserver
