---
- name: Restart pulpcore-api.service
  systemd:
    name: pulpcore-api.service
    enabled: true
    state: restarted
    daemon_reload: true
  become: true

- name: Collect static content
  command: '{{ pulp_install_dir }}/bin/django-admin collectstatic --noinput --link'
  register: staticresult
  changed_when: "staticresult.stdout is not search('\n0 static files')"
  become: true
  become_user: '{{ pulp_user }}'
  notify: Restart pulpcore-api.service
