---
- name: Create user {{ pulp_user }}
  user:
    name: "{{ pulp_user }}"
    shell: /bin/nologin
    home: '{{ pulp_var_dir }}'
    comment: "Pulp user"

- name: Create temp dir for Pulp
  file:
    path: '{{ pulp_var_dir }}/tmp'
    state: directory
    owner: '{{ pulp_user }}'
    group: '{{ pulp_user }}'
    mode: 0775

- name: Create cache dir for Pulp
  file:
    path: '{{ pulp_cache_dir }}'
    state: directory
    owner: '{{ pulp_user }}'
    group: '{{ pulp_user }}'
    mode: 0775

- name: Install pulpcore
  pip:
    name: pulpcore
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'

- name: Install Pulp plugins
  pip:
    name: '{{ item }}'
    state: present
    virtualenv: '{{ pulp_install_dir }}'
  with_items: '{{ pulp_install_plugins }}'
