---
galaxy_info:
  author: Pulp
  description: Pulp Redis
  company: Red Hat
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Fedora
      versions:
        - 30
        - 31
  license: GPL-3.0
dependencies: []
