---
- hosts: all
  roles:
    - pulp-database
    - pulp-workers
    - pulp-resource-manager
    - pulp-webserver
    - pulp-content
    - pulp-devel
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
