---
- block:
    - name: Install SCL package
      package:
        name: 'centos-release-scl'
        state: present
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version|int == 7

    - name: Install PostgreSQL SCL
      package:
        name: 'rh-postgresql96'
        state: present
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version|int == 7

    - name: Enable PostgreSQL SCL
      template:
        src: templates/postgresql_scl_profile.j2
        dest: "{{ postgresql_profile_path }}"
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version|int == 7

    - name: Set listen addresses
      set_fact:
        postgresql_global_config_options:
          - option: listen_addresses
            value: "*"
      when: merged_pulp_settings.databases.default.HOST != 'localhost'

    - name: Install and configure PostgreSQL
      include_role:
        name: geerlingguy.postgresql
  become: yes

- name: Enable debversion extension on pulp db
  postgresql_ext:
    name: debversion
    db: "{{ item.name }}"
  become: true
  become_user: postgres
  loop: "{{ postgresql_databases }}"
