---
- name: Load OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - 'vars'
  tags:
    - always

- import_tasks: nginx.yml
  when: pulp_webserver_server == 'nginx'

- import_tasks: apache.yml
  when: pulp_webserver_server == 'apache'

- import_tasks: firewalld.yml
  when: pulp_configure_firewall in ['firewalld', 'auto']
