---
- import_tasks: nginx.yml
  when: pulp_webserver_server == 'nginx'

- import_tasks: apache.yml
  when: pulp_webserver_server == 'apache'

- import_tasks: firewalld.yml
  when: pulp_configure_firewall in ['firewalld', 'auto']
