---
# installation of nginx on ubuntu doesn't do this automatically
- name: Create nginx user
  user:
    name: nginx
    system: true
  when: ansible_distribution == 'Ubuntu'
  become: yes

- name: Find site-packages directory
  find:
    paths: '{{ pulp_install_dir }}'
    recurse: true
    file_type: directory
    patterns: site-packages
  register: result

- name: Assert one directory has been found
  assert:
    that: '{{ result.matched }} == 1'

- name: Set fact referencing Pulp's static files directory
  set_fact:
    pulp_webserver_static_dir: '{{ result.files[0].path }}/rest_framework'

- block:

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Install Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: reload nginx

    - name: Check installed plugins for nginx snippets
      script:
        cmd: check_snippet.py {{ item.key | regex_replace("pulp-", "pulp_") | quote }} nginx.conf
      args:
        executable: /usr/local/lib/pulp/bin/python
      register: snippets
      with_dict: '{{ pulp_install_plugins }}'
      failed_when: false
      changed_when: false
      check_mode: false

    # FIXME: The ansible output here over the results is very ugly.
    # It may be a lot cleaner if we were to use the command module,
    # above and/or create a temporary data structure.
    - name: Symlink nginx snippets
      file:
        src: "{{ item.stdout_lines | last }}"
        # Note: item.item is pulp_install_plugins
        dest: "/etc/nginx/conf.d/{{ item.item.key | regex_replace('pulp-', 'pulp_') }}"
        state: link
      loop: '{{ snippets.results }}'
      when: item.rc == 0
      notify: reload nginx

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true

  become: true
