---
pulp_install_db: true

# Users should not set this variable, instead using `pulp_settings.databases`
pulp_settings_db_defaults:
    databases:
        default:
            HOST: localhost
            ENGINE: django.db.backends.postgresql_psycopg2
            NAME: pulp
            USER: pulp
            PASSWORD: pulp
