---
# This file is a hack to work around the debian release detection mechanism of the postgres role
# It can be safely removed, once debian 10 is available in the postgres role
__postgresql_version: "11"
__postgresql_data_dir: "/var/lib/postgresql/{{ __postgresql_version }}/main"
__postgresql_bin_path: "/usr/lib/postgresql/{{ __postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ __postgresql_version }}/main"
__postgresql_daemon: "postgresql@{{ postgresql_version }}-main"
__postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
