---
galaxy_info:
  author: Pulp Team
  description: A role that sets up a development environment for Pulp 3, and its plugins
  issue_tracker_url: https://pulp.plan.io/projects/external/issues/new
  license: GPLv2
  company: Red Hat
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - pulp
    - pulpcore
dependencies:
  - pulp
