---
pulp_webserver_apache_package: httpd
pulp_webserver_apache_service: httpd
pulp_webserver_apache_vhost_dir: /etc/httpd/conf.d
pulp_webserver_apache_snippets_dir: /etc/httpd/pulp
pulp_webserver_apache_log_dir: /var/log/httpd
