---
pulp_preq_packages:
  - python3
  - python3-dev
  - python3-venv
  - libpq-dev
  - gcc              # For psycopg2
  - postgresql-11-debversion

# Pulp requires Python 3.6+.
pulp_python_interpreter: /usr/bin/python3
