---
pulp_preq_packages:
  - python3
  - python3-devel
  - python3-libselinux  # For ansible itself
  - make                # For make docs

# Pulp requires Python 3.6+.
pulp_python_interpreter: /usr/bin/python3
