---
- name: Ensure podman apt key is present (Debian-specific)
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable\
    /{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key"
    state: present
  when: ansible_distribution == 'Debian'

- name: Ensure podman repository (Debian-specific)
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable\
    /{{ ansible_distribution }}_{{ ansible_distribution_version }}/ /"
    filename: libcontainers
  when: ansible_distribution == 'Debian'

- name: Install podman package
  package:
    name:
      - podman
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded

- name: Adding podman registries (Debian-specific)
  command: echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | tee /etc/containers/registries.conf
  become: yes
  args:
    creates: /etc/containers
  when: ansible_distribution == 'Debian'

# Needed to allow non-root users to run podman containers on Debian
- name: Enable unprivileged_userns_clone (Debian specific)
  sysctl:
    name: kernel.unprivileged_userns_clone
    value: "1"
  when:
    - ansible_distribution == 'Debian'
    - ansible_virtualization_type != 'docker'

# Needed to allow non-root users to run podman containers on CentOS
- name: Set max_user_namespaces (CentOS specific)
  sysctl:
    name: user.max_user_namespaces
    value: "15000"
  when: ansible_distribution == 'CentOS'
...
