---
- block:

    - name: Install several useful packages (distro-agnostic)
      package:
        name:
          - dstat
          - git
          - htop
          - iotop
          - jnettop
          - jq
          - ncdu
          - tmux
          - tree
          - wget
          - gnupg
        state: present
      retries: "{{ pulp_devel_package_retries }}"
      register: result
      until: result is succeeded

    - name: Install Centos Specific Packages
      package:
        name:
          - python-virtualenvwrapper
          - podman
      when: ansible_distribution == 'CentOS'

    - name: Ensure podman apt key is present (Debian-specific)
      apt_key:
        url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable\
        /{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key"
        state: present
      when: ansible_distribution == 'Debian'

    - name: Ensure podman repository (Debian-specific)
      apt_repository:
        repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable\
        /{{ ansible_distribution }}_{{ ansible_distribution_version }}/ /"
        filename: libcontainers
      when: ansible_distribution == 'Debian'

    - name: Install several useful packages (Debian-specific)
      package:
        name:
          - bash-completion
          - fd-find
          - fzf
          - python3-setuptools
          - virtualenvwrapper
          - ripgrep
          - vim
          - software-properties-common
          - podman
        state: present
      retries: "{{ pulp_devel_package_retries }}"
      register: result
      until: result is succeeded
      when: ansible_distribution == 'Debian'

    - name: Adding podman registries (Debian-specific)
      command: echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | tee /etc/containers/registries.conf
      become: yes
      args:
        creates: /etc/containers
      when: ansible_distribution == 'Debian'

    - name: Install several useful packages (Fedora-specific)
      package:
        name:
          - bash-completion
          - dnf-utils
          - fd-find
          - fzf
          - python-django-bash-completion
          - python3-setuptools
          - python3-virtualenvwrapper
          - ripgrep
          - vim-enhanced
          - podman
        state: present
      retries: "{{ pulp_devel_package_retries }}"
      register: result
      until: result is succeeded
      when: ansible_distribution == 'Fedora'

    - name: "Add {{ pulp_user }} to systemd-journal group"
      user:
        name: "{{ pulp_user }}"
        groups: systemd-journal
        append: yes

  become: true

- block:

    - name: Install requirements for building docs
      pip:
        requirements: '{{ pulp_requirements_dir }}/doc_requirements.txt'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'

    - name: Install requirements for testing locally
      pip:
        requirements: '{{ pulp_requirements_dir }}/test_requirements.txt'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'

    - name: Install requirements for developer scripts
      pip:
        requirements: '{{ pulp_requirements_dir }}/dev_requirements.txt'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'

    - name: Install HTTPie and JWT authentication plugin
      pip:
        name:
          - httpie
          - httpie-jwt-auth
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'

      retries: "{{ pulp_devel_package_retries }}"
      register: result
      until: result is succeeded
      notify: Collect static content

  become: true
  become_user: '{{ pulp_user }}'

- block:

    - name: Create ~/.bashrc.d/
      file:
        path: "{{ developer_user_home }}/.bashrc.d/"
        state: directory

    - name: Define developer aliases in ~/.bashrc.d/
      template:
        src: templates/alias.bashrc.j2
        dest: "{{ developer_user_home }}/.bashrc.d/alias.bashrc"

    - name: Source developer aliases in ~/.bashrc.d/
      blockinfile:
        path: "{{ developer_user_home }}/.bashrc"
        block: |
          if [ -d ~/.bashrc.d ]; then
            for file in ~/.bashrc.d/*; do
              . "$file"
            done
          fi
        marker: "# {mark} Ansible managed block: source bashrc.d/"
        create: yes

    - name: Add Django supplemental bashrc
      template:
        src: templates/django.bashrc.j2
        dest: '{{ developer_user_home }}/.bashrc.d/django.bashrc'
      when: pulp_devel_supplement_bashrc

    - name: Add virtualenv supplemental bashrc
      template:
        src: templates/venv.bashrc.j2
        dest: '{{ developer_user_home }}/.bashrc.d/venv.bashrc'
      when: ansible_distribution != 'Ubuntu'

    - name: Install bindings requirements for testing locally
      shell: >-
        source {{ developer_user_home }}/.bashrc.d/alias.bashrc
        && source {{ developer_user_home }}/.bashrc.d/venv.bashrc
        && pbindings {{ item.key| replace("-", "_") }} python
      args:
        executable: /bin/bash
      with_dict: "{{ pulp_install_plugins }}"

    - name: Add fzf bashrc
      copy:
        src: files/fzf.bashrc
        dest: '{{ developer_user_home }}/.bashrc.d/fzf.bashrc'
      when: ansible_distribution == 'Fedora'

  become: true
  become_user: "{{ developer_user }}"
  when: pulp_devel_supplement_bashrc |bool

- block:

    - name: Create ~/.vimrc if not already present
      copy:
        src: files/vimrc
        dest: "{{ developer_user_home }}/.vimrc"
        force: no

    - name: Create ~/.netrc if not already present
      template:
        src: templates/netrc.j2
        dest: "{{ developer_user_home }}/.netrc"
        force: yes
        mode: 0600

    - name: Create pulp-smash config directory if not already present
      file:
        path: "{{ developer_user_home }}/.config/pulp_smash/"
        state: directory
        recurse: yes

    - name: Create pulp-smash config if not already present
      copy:
        src: files/settings.json
        dest: "{{ developer_user_home }}/.config/pulp_smash/settings.json"

  become: true
  become_user: "{{ developer_user }}"

- block:

    - name: Set the message of the day
      copy:
        src: motd
        dest: /etc/motd

  become: true
