---
- import_tasks: install_basic_packages.yml
  become: true

- import_tasks: install_docs_requirements.yml
  become: true
  become_user: '{{ pulp_user }}'

- import_tasks: bashrc.yml
  become: true
  become_user: "{{ developer_user }}"

- import_tasks: config_files.yml
  become: true
  become_user: "{{ developer_user }}"

- name: Set the message of the day
  copy:
    src: motd
    dest: /etc/motd
  become: true
...
