---
pulp_webserver_server: nginx
pulp_content_host: 127.0.0.1
pulp_content_port: 24816
pulp_api_host: 127.0.0.1
pulp_api_port: 24817
pulp_configure_firewall: auto
pulp_user_home: '/var/lib/pulp'
pulp_static_url: 'assets'
pulp_webserver_static_dir: "{{ pulp_user_home | regex_replace('\\/$', '') }}/{{ pulp_static_url | regex_replace('^\\/|\\/$', '') }}/"
